/**
 * First-admin bootstrap (PRD §7.6/§16): a one-time token is generated by
 * `make token` (or printed to server logs at first boot) and consumed at
 * /setup to create the initial admin. Tokens are stored hashed, expire in 30
 * minutes, and are single-use.
 */

import { AppError } from "@hoodmint/core";
import {
  consumeBootstrapToken,
  type Db,
  insertBootstrapToken,
  user as userTable,
} from "@hoodmint/db";
import { fingerprint, generateToken, safeEqual } from "@hoodmint/secrets";
import { eq, sql } from "drizzle-orm";

export const BOOTSTRAP_TOKEN_TTL_MS = 30 * 60 * 1000;

export interface IssuedToken {
  readonly token: string;
  readonly expiresAt: Date;
}

/** Create a one-time setup token; returns plaintext exactly once. */
export async function issueBootstrapToken(db: Db): Promise<IssuedToken> {
  const token = generateToken(32);
  const expiresAt = new Date(Date.now() + BOOTSTRAP_TOKEN_TTL_MS);
  await insertBootstrapToken(db, fingerprint(token), expiresAt);
  return { token, expiresAt };
}

export async function hasAnyUser(db: Db): Promise<boolean> {
  const rows = await db.select({ count: sql<number>`count(*)::int` }).from(userTable);
  return (rows[0]?.count ?? 0) > 0;
}

/**
 * Consume the token and create the first admin atomically; refuses once any
 * user exists so the window cannot be reopened later.
 */
export async function consumeBootstrapTokenAndCreateAdmin(
  db: Db,
  input: { token: string; email: string; name: string; passwordHash: string },
): Promise<{ userId: string }> {
  return db.transaction(async (tx) => {
    const existing = await tx.select({ count: sql<number>`count(*)::int` }).from(userTable);
    if ((existing[0]?.count ?? 0) > 0) {
      throw new AppError("Forbidden", "setup already completed", { statusCode: 403 });
    }
    const ok = await consumeBootstrapToken(tx, fingerprint(input.token));
    if (!ok) {
      throw new AppError("AuthRequired", "bootstrap token invalid, expired, or used", {
        hint: "generate a fresh token with `make token`",
      });
    }
    const inserted = await tx
      .insert(userTable)
      .values({
        id: crypto.randomUUID(),
        name: input.name,
        email: input.email.toLowerCase(),
        emailVerified: true,
        role: "admin",
      })
      .returning({ id: userTable.id });
    const userId = inserted[0]?.id;
    if (userId === undefined) {
      throw new AppError("Conflict", "failed to create admin user");
    }
    await tx.execute(
      sql`insert into account (id, account_id, provider_id, user_id, password)
          values (${crypto.randomUUID()}, ${input.email.toLowerCase()}, 'credential', ${userId}, ${input.passwordHash})`,
    );
    return { userId };
  });
}

export async function findUserByEmail(db: Db, email: string) {
  const rows = await db
    .select()
    .from(userTable)
    .where(eq(userTable.email, email.toLowerCase()))
    .limit(1);
  return rows[0];
}

export { safeEqual };
