/**
 * HoodMint Radar database schema (PRD §9).
 *
 * Conventions:
 * - Application ids are UUIDv7 generated by PostgreSQL 18's uuidv7().
 * - All timestamps are timestamptz, stored/compared in UTC.
 * - Address columns are lowercase canonical; display checksumming is UI-only.
 * - JSONB only for evidence/raw payloads and provider config — never as a
 *   substitute for relational fields.
 * - Wei, supply, and block numbers are bigint / decimal strings.
 */
import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

const id = () => uuid("id").primaryKey().default(sql`uuidv7()`);
const createdAt = () => timestamp("created_at", { withTimezone: true }).notNull().defaultNow();
const updatedAt = () => timestamp("updated_at", { withTimezone: true }).notNull().defaultNow();

/* ── Better Auth managed tables (PRD §9) ─────────────────────────────────── */

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
  role: text("role", { enum: ["admin", "operator", "viewer"] })
    .notNull()
    .default("viewer"),
  banned: boolean("banned").notNull().default(false),
  banReason: text("ban_reason"),
  banExpires: timestamp("ban_expires", { withTimezone: true }),
  twoFactorEnabled: boolean("two_factor_enabled").notNull().default(false),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    token: text("token").notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    impersonatedBy: text("impersonated_by"),
    /** Stamped by an auth.ts `hooks.after` matcher on /sign-in/passkey only
     *  (ADR 0008) — the WebAuthn step-up gate checks this alongside Better
     *  Auth's own `session.freshAge`, since freshness alone doesn't prove
     *  *which* factor was used and a password/TOTP re-prompt is explicitly
     *  not an acceptable substitute for arming. */
    lastAuthMethod: text("last_auth_method"),
  },
  (t) => [uniqueIndex("session_token_idx").on(t.token)],
);

/** Better Auth passkey plugin's required table (docs.better-auth.com/plugins/passkey). */
export const passkey = pgTable(
  "passkey",
  {
    id: text("id").primaryKey(),
    name: text("name"),
    publicKey: text("public_key").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    credentialID: text("credential_id").notNull(),
    counter: integer("counter").notNull(),
    deviceType: text("device_type").notNull(),
    backedUp: boolean("backed_up").notNull(),
    transports: text("transports"),
    createdAt: timestamp("created_at", { withTimezone: true }),
    aaguid: text("aaguid"),
  },
  (t) => [
    index("passkey_user_idx").on(t.userId),
    uniqueIndex("passkey_credential_idx").on(t.credentialID),
  ],
);

export const account = pgTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
  scope: text("scope"),
  password: text("password"),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

export const twoFactor = pgTable("two_factor", {
  id: text("id").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  secret: text("secret").notNull(),
  backupCodes: text("backup_codes").notNull(),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

/* ── Credentials & providers ─────────────────────────────────────────────── */

export const credentials = pgTable(
  "credentials",
  {
    id: id(),
    /** See CredentialType in repositories/credentials.ts for the authoritative list — kept there, not duplicated here, so it can't drift. */
    type: text("type").notNull(),
    name: text("name").notNull(),
    ciphertext: text("ciphertext").notNull(),
    keyVersion: integer("key_version").notNull(),
    fingerprint: text("fingerprint").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    metadata: jsonb("metadata").$type<Record<string, unknown>>(),
    createdBy: text("created_by").references(() => user.id, { onDelete: "set null" }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index("credentials_type_idx").on(t.type)],
);

export const providers = pgTable(
  "providers",
  {
    id: id(),
    /** opensea | robinhood_rpc | calendar | manual */
    kind: text("kind").notNull(),
    enabled: boolean("enabled").notNull().default(true),
    /** Non-secret config; secrets live in credentials, referenced by id. */
    config: jsonb("config").$type<Record<string, unknown>>().notNull().default({}),
    healthStatus: text("health_status", {
      enum: ["healthy", "degraded", "down", "unknown"],
    })
      .notNull()
      .default("unknown"),
    lastSuccessAt: timestamp("last_success_at", { withTimezone: true }),
    lastErrorCode: text("last_error_code"),
    updatedAt: updatedAt(),
    createdAt: createdAt(),
  },
  (t) => [uniqueIndex("providers_kind_idx").on(t.kind)],
);

/* ── Projects & provenance ───────────────────────────────────────────────── */

export const projects = pgTable(
  "projects",
  {
    id: id(),
    chainId: integer("chain_id").notNull(),
    contractAddress: text("contract_address"),
    name: text("name").notNull(),
    slug: text("slug"),
    imageUrl: text("image_url"),
    // Collection socials from OpenSea `/collections/{slug}` — surfaced in the
    // feed so a scam check does not need a click-through (user ask
    // 2026-08-28). `safelistStatus` is OpenSea's OWN verification
    // ("verified" = blue check), distinct from our `confidence`.
    twitterUsername: text("twitter_username"),
    projectUrl: text("project_url"),
    discordUrl: text("discord_url"),
    safelistStatus: text("safelist_status"),
    socialsFetchedAt: timestamp("socials_fetched_at", { withTimezone: true }),
    /** Last time `/drops/{slug}` was asked about this project (200 or 404).
     *  Drives the re-check of stage-less recent collections (2026-09-02:
     *  yolkies-nft was swept before its SeaDrop schedule existed and then
     *  never asked again). */
    dropCheckedAt: timestamp("drop_checked_at", { withTimezone: true }),
    confidence: text("confidence", {
      enum: ["verified", "corroborated", "single-source", "unverified"],
    })
      .notNull()
      .default("single-source"),
    lifecycleStatus: text("lifecycle_status", {
      enum: ["LIVE", "NEXT", "ENDED", "SOLD_OUT", "PAUSED", "UNKNOWN"],
    })
      .notNull()
      .default("UNKNOWN"),
    /** Denormalized for the feed index below; recomputed on normalization. */
    nextStageStart: timestamp("next_stage_start", { withTimezone: true }),
    firstSeenAt: createdAt(),
    lastSeenAt: updatedAt(),
  },
  (t) => [
    uniqueIndex("projects_contract_idx")
      .on(t.chainId, t.contractAddress)
      .where(sql`contract_address IS NOT NULL`),
    uniqueIndex("projects_slug_idx").on(t.slug).where(sql`slug IS NOT NULL`),
    index("projects_feed_idx").on(t.lifecycleStatus, t.nextStageStart),
    index("projects_first_seen_idx").on(t.firstSeenAt.desc()),
    index("projects_last_seen_idx").on(t.lastSeenAt.desc()),
  ],
);

export const projectAliases = pgTable(
  "project_aliases",
  {
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    providerId: uuid("provider_id")
      .notNull()
      .references(() => providers.id, { onDelete: "cascade" }),
    externalId: text("external_id").notNull(),
    firstSeenAt: createdAt(),
    lastSeenAt: updatedAt(),
  },
  (t) => [
    primaryKey({ columns: [t.providerId, t.externalId] }),
    index("project_aliases_project_idx").on(t.projectId),
  ],
);

export const projectFields = pgTable(
  "project_fields",
  {
    id: id(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    field: text("field").notNull(),
    valueJson: jsonb("value_json").notNull(),
    providerId: uuid("provider_id").references(() => providers.id, { onDelete: "set null" }),
    observedAt: timestamp("observed_at", { withTimezone: true }).notNull(),
    evidenceId: uuid("evidence_id"),
    isWinner: boolean("is_winner").notNull().default(false),
  },
  (t) => [index("project_fields_project_idx").on(t.projectId, t.field, t.observedAt.desc())],
);

export const evidence = pgTable(
  "evidence",
  {
    id: id(),
    providerId: uuid("provider_id").references(() => providers.id, { onDelete: "set null" }),
    kind: text("kind").notNull(),
    fetchedAt: timestamp("fetched_at", { withTimezone: true }).notNull(),
    contentHash: text("content_hash").notNull(),
    /** Sanitized provider payload; secrets/auth headers never stored (PRD §11). */
    sanitizedPayload: jsonb("sanitized_payload"),
  },
  (t) => [index("evidence_fetched_idx").on(t.fetchedAt.desc())],
);

/* ── Stages & supply ─────────────────────────────────────────────────────── */

export const dropStages = pgTable(
  "drop_stages",
  {
    id: id(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    providerStageId: text("provider_stage_id").notNull(),
    version: integer("version").notNull().default(1),
    label: text("label").notNull(),
    type: text("type", {
      enum: ["public", "allowlist", "presale", "gtd", "community", "unknown"],
    })
      .notNull()
      .default("unknown"),
    priceWei: text("price_wei"),
    currency: text("currency"),
    maxPerWallet: integer("max_per_wallet"),
    startsAt: timestamp("starts_at", { withTimezone: true }).notNull(),
    endsAt: timestamp("ends_at", { withTimezone: true }),
    paused: boolean("paused").notNull().default(false),
    rawEvidenceId: uuid("raw_evidence_id").references(() => evidence.id, {
      onDelete: "set null",
    }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex("drop_stages_project_stage_idx").on(t.projectId, t.providerStageId),
    index("drop_stages_start_idx").on(t.startsAt),
  ],
);

export const supplySnapshots = pgTable(
  "supply_snapshots",
  {
    id: id(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    blockNumber: bigint("block_number", { mode: "bigint" }),
    minted: bigint("minted", { mode: "bigint" }).notNull(),
    maxSupply: bigint("max_supply", { mode: "bigint" }),
    observedAt: timestamp("observed_at", { withTimezone: true }).notNull(),
    source: text("source").notNull(),
    verified: boolean("verified").notNull().default(false),
  },
  (t) => [index("supply_snapshots_project_idx").on(t.projectId, t.observedAt.desc())],
);

/* ── On-chain mint data ──────────────────────────────────────────────────── */

export const mintEvents = pgTable(
  "mint_events",
  {
    id: id(),
    chainId: integer("chain_id").notNull(),
    txHash: text("tx_hash").notNull(),
    logIndex: integer("log_index").notNull(),
    blockNumber: bigint("block_number", { mode: "bigint" }).notNull(),
    blockHash: text("block_hash").notNull(),
    projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }),
    recipient: text("recipient").notNull(),
    quantity: integer("quantity").notNull().default(1),
    finalized: boolean("finalized").notNull().default(false),
    observedAt: timestamp("observed_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("mint_events_unique_idx").on(t.chainId, t.txHash, t.logIndex),
    index("mint_events_project_block_idx").on(t.projectId, t.blockNumber),
    index("mint_events_block_idx").on(t.blockNumber),
  ],
);

export const mintAggregates = pgTable(
  "mint_aggregates",
  {
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    bucketStart: timestamp("bucket_start", { withTimezone: true }).notNull(),
    /** "5m" | "1h" */
    bucketSize: text("bucket_size").notNull(),
    quantity: integer("quantity").notNull().default(0),
    uniqueRecipients: integer("unique_recipients").notNull().default(0),
    updatedAt: updatedAt(),
  },
  (t) => [primaryKey({ columns: [t.projectId, t.bucketStart, t.bucketSize] })],
);

/**
 * Exact rolling-one-hour activity prepared by the worker for read paths.
 * Feed requests only read this one-row snapshot; they never aggregate the
 * append-only mint_events table. `computedAt` is retained as provenance so
 * callers can label an absent/stale snapshot instead of inventing freshness.
 */
export const mintActivitySnapshots = pgTable("mint_activity_snapshots", {
  projectId: uuid("project_id")
    .primaryKey()
    .references(() => projects.id, { onDelete: "cascade" }),
  windowStartedAt: timestamp("window_started_at", { withTimezone: true }).notNull(),
  computedAt: timestamp("computed_at", { withTimezone: true }).notNull().defaultNow(),
  quantity: integer("quantity").notNull().default(0),
  uniqueRecipients: integer("unique_recipients").notNull().default(0),
});

/**
 * Whale / holder-concentration analysis (feature-backlog.md §2, shipped
 * 2026-08-22). One row per project — the latest snapshot, not a history
 * (mint_aggregates already owns time-bucketed history; this is a
 * point-in-time "who holds it right now" view refreshed by a maintenance
 * job). Only raw counts are stored; percentages are computed at read time
 * by packages/core's computeHolderConcentration to avoid a derived value
 * drifting out of sync with totalMinted/topHolders.
 */
export const holderSnapshots = pgTable("holder_snapshots", {
  projectId: uuid("project_id")
    .primaryKey()
    .references(() => projects.id, { onDelete: "cascade" }),
  computedAt: timestamp("computed_at", { withTimezone: true }).notNull().defaultNow(),
  totalMinted: integer("total_minted").notNull(),
  uniqueHolders: integer("unique_holders").notNull(),
  /** Top 10 recipients by quantity, descending — see computeHolderConcentration. */
  topHolders: jsonb("top_holders").$type<{ recipient: string; quantity: number }[]>().notNull(),
});

/**
 * Trait rarity ranking (feature-backlog.md §2, shipped 2026-08-22). Same
 * shape/rationale as holderSnapshots above: one row per project, latest
 * snapshot only (not history), admin-triggered refresh (not a background
 * job — bounded by OpenSea Read-quota cost for potentially large
 * collections). Only the top-N rarest tokens are stored, computed by
 * packages/core's computeRarityScores; scores are stored (not
 * re-derivable cheaply without the full collection fetch) but this table
 * is still disposable/re-fetchable, never a system of record.
 */
export const raritySnapshots = pgTable("rarity_snapshots", {
  projectId: uuid("project_id")
    .primaryKey()
    .references(() => projects.id, { onDelete: "cascade" }),
  computedAt: timestamp("computed_at", { withTimezone: true }).notNull().defaultNow(),
  totalTokens: integer("total_tokens").notNull(),
  /** Top 25 rarest tokens, descending by rarityScore — see computeRarityScores. */
  topRarest: jsonb("top_rarest")
    .$type<
      {
        tokenId: string;
        rarityScore: number;
        rank: number;
        traits: { traitType: string; value: string }[];
        imageUrl: string | null;
      }[]
    >()
    .notNull(),
});

export const chainCheckpoints = pgTable(
  "chain_checkpoints",
  {
    chainId: integer("chain_id").notNull(),
    providerId: uuid("provider_id")
      .notNull()
      .references(() => providers.id, { onDelete: "cascade" }),
    blockNumber: bigint("block_number", { mode: "bigint" }).notNull(),
    blockHash: text("block_hash").notNull(),
    updatedAt: updatedAt(),
    createdAt: createdAt(),
  },
  (t) => [primaryKey({ columns: [t.chainId, t.providerId] })],
);

/* ── Eligibility & watchlists ────────────────────────────────────────────── */

export const eligibilityChecks = pgTable(
  "eligibility_checks",
  {
    id: id(),
    walletId: uuid("wallet_id")
      .notNull()
      .references(() => wallets.id, { onDelete: "cascade" }),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    stageId: uuid("stage_id").references(() => dropStages.id, { onDelete: "cascade" }),
    status: text("status", {
      enum: [
        "ELIGIBLE_RESTRICTED",
        "INELIGIBLE_RESTRICTED",
        "PUBLIC_ONLY",
        "AUTH_REQUIRED",
        "UNKNOWN",
        "ERROR",
      ],
    }).notNull(),
    maxMintable: integer("max_mintable"),
    priceWei: text("price_wei"),
    checkedAt: timestamp("checked_at", { withTimezone: true }).notNull(),
    nextDueAt: timestamp("next_due_at", { withTimezone: true }),
    evidenceId: uuid("evidence_id").references(() => evidence.id, { onDelete: "set null" }),
    errorCode: text("error_code"),
  },
  (t) => [
    uniqueIndex("eligibility_unique_idx").on(t.walletId, t.projectId, t.stageId),
    index("eligibility_due_idx").on(t.nextDueAt).where(sql`next_due_at IS NOT NULL`),
    index("eligibility_status_idx").on(t.status, t.checkedAt.desc()),
  ],
);

export const wallets = pgTable(
  "wallets",
  {
    id: id(),
    address: text("address").notNull(),
    label: text("label"),
    enabled: boolean("enabled").notNull().default(true),
    credentialId: uuid("credential_id").references(() => credentials.id, {
      onDelete: "set null",
    }),
    // Owner-authorized managed-key custody (2026-08-28): a burner wallet's
    // AES-256-GCM-sealed private key (JSON SealedSecret as text), enabling
    // the `managed_wallet_key` signer scheme for autonomous multi-wallet
    // minting. Decrypted ONLY in worker memory at fire time, never logged.
    // Fingerprint is safe to display; the blob is never selected into any
    // client-facing payload (listWallets excludes it).
    encryptedSigningKey: text("encrypted_signing_key"),
    signingKeyFingerprint: text("signing_key_fingerprint"),
    signingKeyAddedAt: timestamp("signing_key_added_at", { withTimezone: true }),
    // Worker-owned funding snapshot (2026-09-02): native balance read every
    // minute for managed wallets so admin pages can show "can this wallet
    // pay?" without calling an RPC in a page render. Decimal wei string.
    nativeBalanceWei: text("native_balance_wei"),
    balanceCheckedAt: timestamp("balance_checked_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex("wallets_address_idx").on(t.address)],
);

export const watchlistEntries = pgTable(
  "watchlist_entries",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    createdAt: createdAt(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.projectId] })],
);

/* ── Alerts & notifications ──────────────────────────────────────────────── */

export const alertRules = pgTable("alert_rules", {
  id: id(),
  name: text("name").notNull(),
  type: text("type", {
    enum: [
      "restricted_eligible",
      "stage_starting",
      "watched_live",
      "watched_nearing_sellout",
      "source_failure",
    ],
  }).notNull(),
  enabled: boolean("enabled").notNull().default(true),
  /** { windowsMinutes, quietHours, minSeverity, ... } */
  config: jsonb("config").$type<Record<string, unknown>>().notNull().default({}),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

export const alertChannels = pgTable("alert_channels", {
  id: id(),
  // "discord" and "web_push" added 2026-08-22 (feature-backlog.md) — this
  // column is a plain `text` in every committed migration, not a native
  // Postgres enum or CHECK constraint (see migrations/0000_initial_schema.sql),
  // so widening this TS-level literal union needed no new migration.
  kind: text("kind", { enum: ["telegram", "webhook", "discord", "web_push"] }).notNull(),
  name: text("name").notNull(),
  enabled: boolean("enabled").notNull().default(true),
  /** Sealed JSON: {url} or {botToken, chatId}. */
  credentialId: uuid("credential_id").references(() => credentials.id, {
    onDelete: "set null",
  }),
  config: jsonb("config").$type<Record<string, unknown>>().notNull().default({}),
  lastSuccessAt: timestamp("last_success_at", { withTimezone: true }),
  lastErrorCode: text("last_error_code"),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

export const notificationOutbox = pgTable(
  "notification_outbox",
  {
    id: id(),
    dedupeKey: text("dedupe_key").notNull(),
    alertType: text("alert_type").notNull(),
    walletId: uuid("wallet_id").references(() => wallets.id, { onDelete: "set null" }),
    projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }),
    stageId: uuid("stage_id").references(() => dropStages.id, { onDelete: "set null" }),
    thresholdMinutes: integer("threshold_minutes").notNull().default(0),
    /** Rendered, secret-free message parts for channel adapters. */
    payload: jsonb("payload").$type<Record<string, unknown>>().notNull(),
    status: text("status", {
      enum: ["pending", "inflight", "sent", "failed", "dead"],
    })
      .notNull()
      .default("pending"),
    attempts: integer("attempts").notNull().default(0),
    nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true }).notNull().defaultNow(),
    lastErrorCode: text("last_error_code"),
    sanitizedResponse: text("sanitized_response"),
    createdAt: createdAt(),
    sentAt: timestamp("sent_at", { withTimezone: true }),
  },
  (t) => [
    uniqueIndex("notification_outbox_dedupe_idx").on(t.dedupeKey),
    index("notification_outbox_pending_idx").on(t.status, t.nextAttemptAt),
  ],
);

export const notificationAttempts = pgTable(
  "notification_attempts",
  {
    id: id(),
    outboxId: uuid("outbox_id")
      .notNull()
      .references(() => notificationOutbox.id, { onDelete: "cascade" }),
    channelKind: text("channel_kind").notNull(),
    status: text("status", { enum: ["success", "failure"] }).notNull(),
    attemptAt: timestamp("attempt_at", { withTimezone: true }).notNull(),
    latencyMs: integer("latency_ms").notNull().default(0),
    errorCode: text("error_code"),
    sanitizedResponse: text("sanitized_response"),
  },
  (t) => [index("notification_attempts_outbox_idx").on(t.outboxId)],
);

/* ── Execution & signals foundation (ADR 0003–0008) ──────────────────────────
 * Phase 0/1 data model only. No code path in this repository holds a
 * spend-capable signing key or broadcasts a transaction yet — see
 * docs/execution-architecture.md and docs/decisions/0003..0008. `signers`,
 * `mintPlans`, and `executionAttempts` exist so the shape is reviewable and
 * migratable ahead of Phase 1 (browser-wallet-signed, zero server custody);
 * `rpcEndpoints` and `signals` are live Phase 0 read-only additions.
 * ────────────────────────────────────────────────────────────────────────── */

export const rpcEndpoints = pgTable(
  "rpc_endpoints",
  {
    id: id(),
    chainId: integer("chain_id").notNull(),
    label: text("label").notNull(),
    httpUrl: text("http_url").notNull(),
    wsUrl: text("ws_url"),
    /** Lower fires first; ties broken by insertion order. */
    priority: integer("priority").notNull().default(0),
    enabled: boolean("enabled").notNull().default(true),
    /** Auth (API key in header/query) resolved via credentials, never stored raw here. */
    credentialId: uuid("credential_id").references(() => credentials.id, {
      onDelete: "set null",
    }),
    healthStatus: text("health_status", {
      enum: ["healthy", "degraded", "down", "unknown"],
    })
      .notNull()
      .default("unknown"),
    lastSuccessAt: timestamp("last_success_at", { withTimezone: true }),
    lastErrorCode: text("last_error_code"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index("rpc_endpoints_chain_idx").on(t.chainId, t.enabled, t.priority)],
);

export const signers = pgTable(
  "signers",
  {
    id: id(),
    chainId: integer("chain_id").notNull(),
    /** The owner's hardware-wallet EOA — the asset owner, never an automated signer. */
    ownerAddress: text("owner_address").notNull(),
    /** browser_wallet: Phase 1, zero server custody. eip7702_safe_zodiac /
     *  custom_executor: Phase 2 delegated custody per ADR 0004. */
    scheme: text("scheme", {
      enum: ["browser_wallet", "eip7702_safe_zodiac", "custom_executor"],
    }).notNull(),
    delegateContractAddress: text("delegate_contract_address"),
    /** Sealed session-key credential; null for browser_wallet. Only
     *  packages/signing may ever resolve this (ADR 0004/0005). */
    sessionKeyCredentialId: uuid("session_key_credential_id").references(() => credentials.id, {
      onDelete: "set null",
    }),
    /** Coarse, conservative on-chain backstop for this delegation (ADR 0004
     *  cap tiering) — wei, decimal string. Not the per-plan ceiling. */
    onchainSpendCeilingWei: text("onchain_spend_ceiling_wei"),
    status: text("status", { enum: ["pending", "active", "revoked"] })
      .notNull()
      .default("pending"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index("signers_owner_idx").on(t.chainId, t.ownerAddress)],
);

export const mintPlans = pgTable(
  "mint_plans",
  {
    id: id(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    stageId: uuid("stage_id").references(() => dropStages.id, { onDelete: "set null" }),
    /** Operator-supplied fire instant (Admin → Special mints), stored UTC.
     *  Overrides the linked stage's `startsAt` as the precision hot-loop's
     *  fire target — `coalesce(fire_at, drop_stages.starts_at)`. Null means
     *  "auto-detect from the stage", which stays the default everywhere
     *  else. A plan may carry a `fire_at` with NO stage at all (a mint whose
     *  phase OpenSea never published) and still be precision-timed. */
    fireAt: timestamp("fire_at", { withTimezone: true }),
    signerId: uuid("signer_id").references(() => signers.id, { onDelete: "set null" }),
    walletId: uuid("wallet_id")
      .notNull()
      .references(() => wallets.id, { onDelete: "cascade" }),
    quantity: integer("quantity").notNull().default(1),
    /** Precise per-arm ceiling; must be <= signer.onchainSpendCeilingWei
     *  (ADR 0004 cap tiering). Wei, decimal string. */
    perPlanCeilingWei: text("per_plan_ceiling_wei").notNull(),
    status: text("status", {
      enum: ["draft", "armed", "executing", "executed", "expired", "cancelled", "failed"],
    })
      .notNull()
      .default("draft"),
    armedAt: timestamp("armed_at", { withTimezone: true }),
    /** Arm auto-expires; the armed→executing transition is one atomic
     *  WHERE-clause condition over (status, armedUntil, spend-to-date) — see
     *  packages/core mint-plan policy check (ADR 0005). Never a separate job. */
    armedUntil: timestamp("armed_until", { withTimezone: true }),
    armedByUserId: text("armed_by_user_id").references(() => user.id, { onDelete: "set null" }),
    /** ADR 0009, item P4: an OpenSea buildTransaction() response fetched
     *  speculatively (during the pre-build worker pass, not at claim time)
     *  so claimArmedMintPlan's caller can skip that round-trip on the
     *  common path. Null until pre-built; the simulate step in
     *  runExecutionPipeline is unaffected either way — this only ever
     *  changes where the calldata came from, never skips validating it. */
    cachedTx: jsonb("cached_tx").$type<{
      to: string;
      data: string;
      valueWei: string;
      chainId: number;
    } | null>(),
    /** TTL anchor for cachedTx — a stale cache (stage/price/proof may have
     *  changed) is rebuilt fresh at claim time, same as if no cache existed. */
    cachedTxAt: timestamp("cached_tx_at", { withTimezone: true }),
    /** Pre-signed raw tx (managed_wallet_key plans only, ADR 0009 fast path):
     *  signed during the pre-warm window so the fire instant is ONE
     *  sendRawTransaction. Spend-capable artifact — short TTL, purged on key
     *  revoke / wallet delete / terminal plan state, never logged. */
    presignedRawTx: text("presigned_raw_tx"),
    presignedNonce: integer("presigned_nonce"),
    presignedTxHash: text("presigned_tx_hash"),
    presignedAt: timestamp("presigned_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index("mint_plans_status_idx").on(t.status, t.armedUntil)],
);

export const executionAttempts = pgTable(
  "execution_attempts",
  {
    id: id(),
    planId: uuid("plan_id")
      .notNull()
      .references(() => mintPlans.id, { onDelete: "cascade" }),
    status: text("status", {
      enum: [
        "simulating",
        "simulated_ok",
        "simulated_revert",
        // The pipeline reached ready_for_browser_signature (ADR 0008 Phase
        // 1): a real, unsigned transaction is waiting for the owner's own
        // browser wallet. Nothing has been signed or broadcast yet.
        "awaiting_signature",
        "broadcast",
        "provisional_success",
        "confirmed",
        "failed",
      ],
    }).notNull(),
    /** Sanitized eth_call/callStatic result — mandatory pre-flight, never
     *  bypassable (ADR 0005). */
    simulationResult: jsonb("simulation_result").$type<Record<string, unknown>>(),
    /** Set only when status='awaiting_signature' — the exact unsigned
     *  transaction the browser wallet will be asked to sign. No secret
     *  ever lives here; this is the same payload packages/signing's
     *  toBrowserSignRequest would hand a client. */
    pendingTx: jsonb("pending_tx").$type<{
      to: string;
      data: string;
      valueWei: string;
      chainId: number;
    }>(),
    txHash: text("tx_hash"),
    rpcEndpointId: uuid("rpc_endpoint_id").references(() => rpcEndpoints.id, {
      onDelete: "set null",
    }),
    gasUsed: bigint("gas_used", { mode: "bigint" }),
    effectiveGasPriceWei: text("effective_gas_price_wei"),
    errorCode: text("error_code"),
    attemptAt: timestamp("attempt_at", { withTimezone: true }).notNull().defaultNow(),
    confirmedAt: timestamp("confirmed_at", { withTimezone: true }),
  },
  (t) => [
    index("execution_attempts_plan_idx").on(t.planId),
    index("execution_attempts_status_idx").on(t.status),
  ],
);

export const signals = pgTable(
  "signals",
  {
    id: id(),
    projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }),
    /** Contract address, @handle, or collection slug when not yet linked to a project. */
    subject: text("subject").notNull(),
    /** e.g. "x_mentions" | "x_scam_list" | "onchain_velocity" (ADR 0007). */
    source: text("source").notNull(),
    kind: text("kind", { enum: ["hype", "risk"] }).notNull(),
    score: integer("score").notNull(),
    /** Deliberately distinct from projects.confidence (ADR 0007): this rates
     *  trust in a hype/risk read, never identity/schedule fact — a loud
     *  Twitter mob must never be able to raise a project's own confidence. */
    confidence: text("confidence", {
      enum: ["corroborated", "single-source", "unverified", "stale"],
    })
      .notNull()
      .default("unverified"),
    evidence: jsonb("evidence").$type<Record<string, unknown>>(),
    observedAt: timestamp("observed_at", { withTimezone: true }).notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    index("signals_project_idx").on(t.projectId, t.observedAt.desc()),
    index("signals_subject_idx").on(t.subject, t.source),
  ],
);

/* ── Operations ──────────────────────────────────────────────────────────── */

export const scanRuns = pgTable(
  "scan_runs",
  {
    id: id(),
    providerId: uuid("provider_id").references(() => providers.id, { onDelete: "set null" }),
    kind: text("kind").notNull(),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
    finishedAt: timestamp("finished_at", { withTimezone: true }),
    status: text("status", { enum: ["running", "success", "partial", "failed"] }).notNull(),
    counts: jsonb("counts").$type<Record<string, number>>(),
    errorCode: text("error_code"),
    correlationId: text("correlation_id"),
  },
  (t) => [index("scan_runs_started_idx").on(t.startedAt.desc())],
);

export const auditLogs = pgTable(
  "audit_logs",
  {
    id: id(),
    actorUserId: text("actor_user_id").references(() => user.id, { onDelete: "set null" }),
    action: text("action").notNull(),
    targetType: text("target_type"),
    targetId: text("target_id"),
    result: text("result", { enum: ["success", "failure"] }).notNull(),
    /** Redacted metadata only — never before/after secret values (PRD §11). */
    metadata: jsonb("metadata").$type<Record<string, unknown>>(),
    correlationId: text("correlation_id"),
    createdAt: createdAt(),
  },
  (t) => [index("audit_logs_created_idx").on(t.createdAt.desc())],
);

export const settings = pgTable("settings", {
  key: text("key").primaryKey(),
  value: jsonb("value").$type<unknown>().notNull(),
  updatedAt: updatedAt(),
});

export const bootstrapTokens = pgTable(
  "bootstrap_tokens",
  {
    id: id(),
    tokenHash: text("token_hash").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    usedAt: timestamp("used_at", { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [uniqueIndex("bootstrap_tokens_hash_idx").on(t.tokenHash)],
);

export type User = typeof user.$inferSelect;
export type Project = typeof projects.$inferSelect;
export type DropStage = typeof dropStages.$inferSelect;
export type Wallet = typeof wallets.$inferSelect;
export type Credential = typeof credentials.$inferSelect;
export type ProviderRow = typeof providers.$inferSelect;
export type MintEvent = typeof mintEvents.$inferSelect;
export type EligibilityCheck = typeof eligibilityChecks.$inferSelect;
export type NotificationOutboxRow = typeof notificationOutbox.$inferSelect;
export type ScanRun = typeof scanRuns.$inferSelect;
export type AuditLog = typeof auditLogs.$inferSelect;
export type AlertChannel = typeof alertChannels.$inferSelect;
export type RpcEndpoint = typeof rpcEndpoints.$inferSelect;
export type Signer = typeof signers.$inferSelect;
export type MintPlan = typeof mintPlans.$inferSelect;
export type ExecutionAttempt = typeof executionAttempts.$inferSelect;
export type Signal = typeof signals.$inferSelect;
