# Shared helpers for start-dev / start-prod / env-setup / stop-*.
# shellcheck shell=bash

if [ -z "${SCRIPT_DIR:-}" ]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi
if [ -z "${ROOT:-}" ]; then
  ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
fi
# shellcheck source=dev-ports.sh
source "${SCRIPT_DIR}/dev-ports.sh"

say() { printf '\033[36m[%s]\033[0m %s\n' "${ENV_LIB_TAG:-hoodmint}" "$*"; }
err() { printf '\033[31m[%s]\033[0m %s\n' "${ENV_LIB_TAG:-hoodmint}" "$*" >&2; }
ok() { printf '\033[32m[%s]\033[0m %s\n' "${ENV_LIB_TAG:-hoodmint}" "$*"; }

env_get() {
  local key="$1"
  [ -f "${ROOT}/.env" ] || return 0
  grep -E "^${key}=" "${ROOT}/.env" | head -1 | cut -d= -f2- || true
}

upsert_env() {
  local key="$1" value="$2"
  local file="${ROOT}/.env"
  if [ ! -f "$file" ]; then
    printf '%s=%s\n' "$key" "$value" >"$file"
    return
  fi
  if grep -qE "^${key}=" "$file"; then
    if sed --version >/dev/null 2>&1; then
      sed -i "s|^${key}=.*|${key}=${value}|" "$file"
    else
      sed -i '' "s|^${key}=.*|${key}=${value}|" "$file"
    fi
  else
    printf '%s=%s\n' "$key" "$value" >>"$file"
  fi
}

gen_key() { openssl rand -base64 32 | tr -d '\n'; }

ensure_secret() {
  local name="$1" value
  value="$(env_get "$name")"
  if [ -z "${value}" ]; then
    upsert_env "$name" "$(gen_key)"
    say "generated ${name}"
    return 0
  fi
  say "${name} already set — left untouched"
}

port_busy() {
  local port="$1"
  if command -v lsof >/dev/null 2>&1; then
    lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1
    return $?
  fi
  return 1
}

http_code() {
  local url="$1" code
  code="$(curl -sS -o /dev/null -w '%{http_code}' --max-time 3 "$url" 2>/dev/null || true)"
  case "$code" in
    2?? | 3?? | 4?? | 5??) printf '%s\n' "$code" ;;
    *) printf '000\n' ;;
  esac
}

wait_http() {
  local url="$1" tries="${2:-120}"
  local i code
  code="000"
  for i in $(seq 1 "$tries"); do
    code="$(http_code "$url")"
    if [ "$code" = "200" ]; then
      return 0
    fi
    sleep 1
  done
  err "timed out waiting for ${url} (last HTTP ${code:-none})"
  return 1
}

pid_alive() {
  local file="$1"
  [ -f "$file" ] || return 1
  local pid
  pid="$(cat "$file" 2>/dev/null || true)"
  [ -n "${pid}" ] && kill -0 "$pid" 2>/dev/null
}

require_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    err "Docker is not installed."
    err "Install Docker Desktop (or Engine + Compose v2), then re-run."
    return 1
  fi
  if ! docker info >/dev/null 2>&1; then
    err "Docker daemon is not running."
    err "Start Docker Desktop, wait until it is healthy, then re-run."
    return 1
  fi
  return 0
}

require_openssl() {
  if ! command -v openssl >/dev/null 2>&1; then
    err "openssl is required to generate APP_ENCRYPTION_KEY / BETTER_AUTH_SECRET."
    return 1
  fi
}

print_setup_guide() {
  local mode="${1:-dev}"
  cat <<EOF

HoodMint Radar — environment setup guide (${mode})

  1. Install Docker Desktop (or Engine + Compose v2) and start it.
  2. From the repo root:
       cp .env.example .env
       scripts/env-setup.sh --mode=${mode}
     That creates/fills secrets. It never overwrites a non-empty secret.
  3. Required in .env (no insecure production defaults):
       APP_ENCRYPTION_KEY   # 32-byte base64 — generated by env-setup
       BETTER_AUTH_SECRET   # ≥32 chars — generated by env-setup
       APP_URL              # http://localhost:${HOODMINT_WEB_PORT} for local
                            # https://your-domain for a public deploy
       APP_ENV              # development | production
       PORT=${HOODMINT_WEB_PORT}
       WORKER_HEALTH_PORT=${HOODMINT_WORKER_HEALTH_PORT}
       DATABASE_URL=postgres://hoodmint:hoodmint@127.0.0.1:${HOODMINT_PG_PORT}/hoodmint
       VALKEY_URL=redis://127.0.0.1:${HOODMINT_VALKEY_PORT}/0
     Compose overrides DATABASE_URL / VALKEY_URL to the Docker DNS names
     inside containers. Do not put a public password in git.
  4. Optional (can also be set later in Admin after /setup):
       OPENSEA_API_KEY, OPENSEA_WALLET_PAT, RPC_URL
  5. Start:
       scripts/start-dev.sh     # local Next + stores on :${HOODMINT_WEB_PORT}
       scripts/start-prod.sh    # Docker production posture on :${HOODMINT_WEB_PORT}
  6. First admin:
       make token
       open http://localhost:${HOODMINT_WEB_PORT}/setup

EOF
}
